In [1]:
# let's now import all the required libraries
import selenium
import pandas as pd
from selenium import webdriver

# to add timer
import time

# to use the keyborad keys
from selenium.webdriver.common.keys import Keys

# to remove pop ups
from selenium.webdriver.common.alert import Alert

In [2]:
#to display all text
pd.set_option('display.max_colwidth',None)

#### Q1. Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name,experience_required. You have to scrape first 10 jobs data.

In [12]:
#Let's first connect to the webdriver
driver=webdriver.Chrome('chromedriver.exe')

In [13]:
url="https://www.naukri.com/"
driver.get(url)

In [14]:
#finding element for job search bar
search_job = driver.find_element_by_id('qsb-keyword-sugg')
search_job

In [15]:
# write on search bar
search_job.send_keys('Data Analyst')

In [16]:
# now finding location search bar and writing on it 

search_loc = driver.find_element_by_id('qsb-location-sugg')
search_loc.send_keys('Bangalore')

In [17]:
# Using xpath ,clicking the 'Search' button

search_btn = driver.find_element_by_xpath("//button[@class='btn']")

search_btn.click()

In [10]:
# so lets extract all the tags having the job-titles

titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")

# to extract job names from above webelements
job_titles=[]
for i in titles_tags:
    job_titles.append(i.text)

# to extract all the tags having the company names
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")

# to extract company names from above tags
company_names=[]
for i in companies_tags:
    company_names.append(i.text)

# to extract all the tags having the experience
experience_tags = driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']//span[1]")

# to extract experience text from above tags
exp=[]
for i in experience_tags:
    exp.append(i.text)

# to extract all the tags having the location
location_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']//span[1]")

# to extract location text
job_location=[]
for i in location_tags:
    job_location.append(i.text)
    
# creating a dataframe
jobs=pd.DataFrame({})
jobs['title']=job_titles[0:10]
jobs['company']=company_names[0:10]
jobs['experience']=exp[0:10]
jobs['location']=job_location[0:10]

jobs

,title,company,experience,location
0,Data Scientist / Data Analyst -Business Analyst,Inflexion Analytix Private Limited,0-3 Yrs,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/..."
1,Data Analyst,GlaxoSmithKline Pharmaceuticals Limited,0-2 Yrs,Bangalore/Bengaluru
2,Data Analyst,Shell India Markets Private Limited,5-8 Yrs,Bangalore/Bengaluru
3,Data Analyst,Applied Materials,7-10 Yrs,Bangalore/Bengaluru
4,Hiring For Data Analyst/ MIS Reporting Analyst...,PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt Ltd,2-4 Yrs,Bangalore/Bengaluru
5,Hiring Data Analysts For E commerce Platform |...,Allegis Services India Pvt. Ltd.,0-5 Yrs,Bangalore/Bengaluru
6,DA - Urgent Opening For Data Analyst BFSI Doma...,Tata Consultancy Services Ltd.,4-9 Yrs,"Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab..."
7,Data Analyst - Informatica MDM,Shell India Markets Private Limited,6-9 Yrs,Bangalore/Bengaluru
8,Data Analyst,Shell India Markets Private Limited,5-8 Yrs,Bangalore/Bengaluru
9,Assistant Vice President - MIS & Reporting ( B...,INTERTRUSTVITEOS CORPORATE AND FUND SERVICES P...,12-18 Yrs,"Mumbai, Bangalore/Bengaluru"

#### Q.2 Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name,experience_required. You have to scrape first 10 jobs data.

#### Please note that you have to scrape full job description.

In [39]:
# Let's first connect to the webdriver
driver=webdriver.Chrome('chromedriver.exe')

In [40]:
# opening the website
url="https://www.naukri.com/"
driver.get(url)

In [41]:
# getting the job search bar web-element
job_search=driver.find_element_by_id("qsb-keyword-sugg")

# writing on job search bar
job_search.send_keys("Data Analyst")

# getting the location search bar web element
loc_search=driver.find_element_by_id("qsb-location-sugg")

# writing on location search bar
loc_search.send_keys("Bangalore")

#getting the search button web element
search_btn=driver.find_element_by_xpath("//button[@class='btn']")

#clicking the search button
search_btn.click()

In [42]:
# get job title tags
title_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
#get job title text from above tags
titles=[]
titles.clear()
for i in title_tags:
    titles.append(i.text)

main_window=driver.current_window_handle
len(titles)

20

In [43]:
companies=[]
companies.clear()

locations=[]
locations.clear()

exp=[]
exp.clear()

descriptions=[]
descriptions.clear()

jobs=pd.DataFrame({})

for i in range(0,len(titles)):
    #storing the webelement for [i]th job description
    temp_tag=title_tags[i]
    #clicking on the [i]th job description
    temp_tag.click()
    
    #storing the window handle of new tab
    child_win=driver.window_handles[i+1]
    
    # working on child window webelements
    driver.switch_to.window(child_win)
    
     # get company name tag
    comp_tag=driver.find_element_by_xpath("//*[@class='jd-header-comp-name' or @class='cpName f14']")
    #get company name text from above tags
    companies.append(comp_tag.text)
    
    #get location tags
    location_tag=driver.find_element_by_xpath("//*[@class='loc' or @class='cityLinks']")
    #get location text from above tag
    locations.append(location_tag.text)
    
    # get experience tags
    experience_tag = driver.find_element_by_xpath("//*[@class='exp' or @class='slide-meta-exp pull-left']")
    #get experience text from above
    exp.append(experience_tag.text)
    
    # get description tag
    descr_tag=driver.find_element_by_xpath("//*[@class='dang-inner-html' or @class='clearboth description']")
    #get description text from above
    descriptions.append(descr_tag.text)
    
    driver.switch_to.window(main_window)
    del temp_tag
    
#enter data into dataframe
jobs['titles']=titles
jobs['company']=companies
jobs['Location']=locations
jobs['Experience']=exp
jobs['Job Description']=descriptions

In [44]:
jobs

,titles,company,Location,Experience,Job Description
0,Data Scientist / Data Analyst -Business Analyst,Inflexion Analytix Private Limited,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...",0 - 3 years,Job Role : Data Scientist/Data Analyst /Busine...
1,Data Analyst,GlaxoSmithKline Pharmaceuticals Limited,Bangalore/Bengaluru,from 0 to 2 year(s) of Experience,The ideal candidate would be highly experience...
2,Hiring Data Analysts For E commerce Platform |...,Allegis Services India Pvt. Ltd.,Bangalore/Bengaluru,from 0 to 5 year(s) of Experience,TEKsystems is a part of Allegis Services Group...
3,Data Analyst,Shell India Markets Private Limited4.1(622 Rev...,Bangalore/Bengaluru,5 - 8 years,The Role\n*Job Description\nIT Services and Op...
4,Data Analyst,Applied Materials,Bangalore/Bengaluru,from 7 to 10 year(s) of Experience,General Profile: This position will be require...
5,Hiring For Data Analyst/ MIS Reporting Analyst...,PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt L...,Bangalore/Bengaluru,2 - 4 years,Greetings from PRA Health Sciences.\n\nJob Rol...
6,DA - Urgent Opening For Data Analyst BFSI Doma...,Tata Consultancy Services Ltd.4.0(21048 Reviews),"Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",4 - 9 years,Functional Data Analyst\n4-10 Years\nMinimum e...
7,Data Analyst - Informatica MDM,Shell India Markets Private Limited4.1(622 Rev...,Bangalore/Bengaluru,6 - 9 years,The Role\nTypically:\n• Manages key elements o...
8,Data Analyst,Shell India Markets Private Limited4.1(622 Rev...,Bangalore/Bengaluru,5 - 8 years,The Role\nIT Services and Operations (ITSO) pr...
9,Assistant Vice President - MIS & Reporting ( B...,INTERTRUSTVITEOS CORPORATE AND FUND SERVICES P...,"Mumbai, Bangalore/Bengaluru",12 - 18 years,Business Title/Designation - Assistant Vice Pr...
10,Data Analyst,Myntra Designs Pvt. Ltd.4.2(741 Reviews),Bangalore/Bengaluru,3 - 6 years,About the CE Team:\nThe Customer Experience te...
11,Data Analyst,Myntra Designs Pvt. Ltd.4.2(741 Reviews),Bangalore/Bengaluru,3 - 6 years,About the CE Team:\nThe Customer Experience te...
12,Data Analyst,Myntra Designs Pvt. Ltd.4.2(741 Reviews),Bangalore/Bengaluru,4 - 9 years,"Data Analyst in WFM & Analytics @ Myntra, Bang..."
13,Data Analyst,Myntra Designs Pvt. Ltd.4.2(741 Reviews),Bangalore/Bengaluru,4 - 8 years,About the CE Team:\nThe Customer Experience te...
14,Data Analyst,Myntra Designs Pvt. Ltd.4.2(741 Reviews),Bangalore/Bengaluru,3 - 6 years,About the CE Team:\nThe Customer Experience te...
15,Data Analyst,SA Tech Software (I) Pvt. Ltd.4.2(31 Reviews),"Kolkata, Pune, Chennai, Bangalore/Bengaluru, D...",1 - 3 years,"Job Description,\n\nExperience - 1 to 3\nNotic..."
16,Data Analyst - Work from Home,POWER STORES E COMMERCE PRIVATE LIMITED,"Pune, Bangalore/Bengaluru, Mumbai (All Areas)",2 - 5 years,POSITION FUNCTION:\nData analyst responsibilit...
17,LTI Hiring Business Data Analyst - Risk Reporting,Larsen & Toubro Infotech Limited3.8(2055 Reviews),"Pune, Chennai, Bangalore/Bengaluru",7 - 10 years,ILTI Hiring Business Analyst / Data Analyst - ...
18,Sybase SQL with Post trade/ settlement Data An...,Larsen & Toubro Infotech Limited3.8(2055 Reviews),"Mumbai, Hyderabad/Secunderabad, Pune, Chennai,...",5 - 9 years,Roles and Responsibilities\nJD for the Data An...
19,Senior/Regular Business Analyst / Data Analyst,Luxoft4.5(47 Reviews),Bangalore/Bengaluru,3 - 6 years,Responsibilities\nLooking for Senior Business ...

## Q.3 same job search like above with location and salary filters

In [45]:
# connect to the web driver
driver=webdriver.Chrome('chromedriver.exe')

In [46]:
# open the website
url="https://www.naukri.com"
driver.get(url)

In [47]:
# getting the job search bar web-element
job_search=driver.find_element_by_id("qsb-keyword-sugg")

# writing on job search bar
job_search.send_keys("Data Scientist")

#getting the search button web element
search_btn=driver.find_element_by_xpath("//button[@class='btn']")

#clicking the search button
search_btn.click()

In [49]:
# getting the webelement for 'Delhi/NCR' checkbox
loc_chkbx=driver.find_element_by_xpath("//span[@title='Delhi / NCR']")
#clicking the checkbox
loc_chkbx.click()

In [50]:
# getting the webelement for '3-6 lakhs' checkbox
sal_chkbx=driver.find_element_by_xpath("//span[@title='3-6 Lakhs']")
#clicking the checkbox
sal_chkbx.click()

In [51]:
# refresh the page
driver.refresh()

In [52]:
# get job title tags
title_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
#get job title text from above tags
titles=[]
titles.clear()
for i in title_tags:
    titles.append(i.text)

main_window=driver.current_window_handle
len(titles)

20

In [53]:
companies=[]
companies.clear()

locations=[]
locations.clear()

exp=[]
exp.clear()

descriptions=[]
descriptions.clear()

jobs_1=pd.DataFrame({})

for i in range(0,len(titles)):
    #storing the webelement for [i]th job description
    temp_tag=title_tags[i]
    #clicking on the [i]th job description
    temp_tag.click()
    
    #storing the window handle of new tab
    child_win=driver.window_handles[i+1]
    
    # working on child window webelements
    driver.switch_to.window(child_win)
    
     # get company name tag
    comp_tag=driver.find_element_by_xpath("//*[@class='jd-header-comp-name' or @class='cpName f14']")
    #get company name text from above tags
    companies.append(comp_tag.text)
    
    #get location tags
    location_tag=driver.find_element_by_xpath("//*[@class='loc' or @class='cityLinks']")
    #get location text from above tag
    locations.append(location_tag.text)
    
    # get experience tags
    experience_tag = driver.find_element_by_xpath("//*[@class='exp' or @class='slide-meta-exp pull-left']")
    #get experience text from above
    exp.append(experience_tag.text)
    
    # get description tag
    descr_tag=driver.find_element_by_xpath("//*[@class='dang-inner-html' or @class='clearboth description']")
    #get description text from above
    descriptions.append(descr_tag.text)
    
    driver.switch_to.window(main_window)
    del temp_tag
    
#enter data into dataframe
jobs_1['titles']=titles
jobs_1['company']=companies
jobs_1['Location']=locations
jobs_1['Experience']=exp
jobs_1['Job Description']=descriptions

In [54]:
jobs_1

,titles,company,Location,Experience,Job Description
0,Data Scientist / Data Analyst -Business Analyst,Inflexion Analytix Private Limited,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...",0 - 3 years,Job Role : Data Scientist/Data Analyst /Busine...
1,Data Scientist,IBM India Pvt. Limited,Noida,from 4 to 9 year(s) of Experience,"Introduction\nAs a Data Scientist at IBM, you ..."
2,Excellent opportunity For Data Scientist,NEC CORPORATION INDIA PRIVATE LIMITED3.4(13 Re...,"Noida, Bangalore/Bengaluru",3 - 7 years,Title\n\nData Scientist\nPosition Summary\n\nP...
3,Data Scientist,Mobikwik3.7(104 Reviews),"New Delhi, Gurgaon/Gurugram, Delhi / NCR",3 - 5 years,Responsibilities\n\n• Leverage advanced Machin...
4,DATA Scientist – Gurgaon (Exp 3-6 years),CRESCENDO GLOBAL LEADERSHIP HIRING INDIA PRIVA...,Gurgaon/Gurugram,from 3 to 6 year(s) of Experience,A data visualization and data modelling opport...
5,DATA Scientist – Gurgaon (Exp 3-6 years),CRESCENDO GLOBAL LEADERSHIP HIRING INDIA PRIVA...,Gurgaon/Gurugram,from 3 to 6 year(s) of Experience,A data visualization and data modelling opport...
6,Data Scientist - Noida/ B'lore,NEC CORPORATION INDIA PRIVATE LIMITED3.4(13 Re...,"Noida, Bangalore/Bengaluru",3 - 8 years,Title Data Scientist\nPosition Summary Provide...
7,Data Scientist,Cloudstrats Technologies Private Limited2.6(10...,"Bangalore/Bengaluru, Delhi / NCR, Mumbai (All ...",5 - 8 years,"Organize and analyze large, diverse data sets ..."
8,Data Scientist/ Data Analyst/ Data Engineer,LANCE LABS PRIVATE LIMITED,"Noida, Chennai",0 - 3 years,- Ability to use analytics to understand how b...
9,Data Scientist - Python & Machine Learning,FUTURES AND CAREERS,"Hyderabad/Secunderabad, Pune, Bangalore/Bengal...",2 - 7 years,Roles and Responsibilities\nExperience : 3+ Ye...
10,Data Scientist - Python & Machine Learning,FUTURES AND CAREERS,"Hyderabad/Secunderabad, Pune, Chennai, Bangalo...",2 - 7 years,Roles and Responsibilities\nExperience : 3+ Ye...
11,Data Scientist - Python / Machine Learning / T...,FUTURES AND CAREERS,"Mumbai, Hyderabad/Secunderabad, Bangalore/Beng...",3 - 8 years,Roles and Responsibilities\nExperience : 4+ Ye...
12,Data Scientist - Python & Machine Learning,FUTURES AND CAREERS,"Hyderabad/Secunderabad, Bangalore/Bengaluru, D...",2 - 7 years,Roles and Responsibilities\nExperience : 3+ Ye...
13,Data Scientist,Country Veggie,"Bharuch, Jaipur, Bhopal, Mumbai, Jhansi, Nagpu...",1 - 3 years,"Responsibilities\nSelecting features, building..."
14,Senior Data Scientist II 5+ yrs II Gurgaon,Zenatix Solutions Private Limited4.0(14 Reviews),Gurgaon/Gurugram,5 - 10 years,Job Responsibilities:\n\nYou will be developin...
15,Senior Data Scientist,iNICU,Delhi,1 - 5 years,Senior Data Scientist We are inviting applicat...
16,Data Scientist - Python / Machine Learning / T...,FUTURES AND CAREERS,"Hyderabad/Secunderabad, Bangalore/Bengaluru, D...",3 - 8 years,Roles and Responsibilities\nExperience : 4+ Ye...
17,Data Scientist - Python & Machine Learning (IS...,FUTURES AND CAREERS,"Hyderabad/Secunderabad, Bangalore/Bengaluru, D...",3 - 8 years,Roles and Responsibilities\nExperience : 3+ Ye...
18,Data Scientist,BlackBuck3.7(577 Reviews),"Gurgaon/Gurugram, Bangalore/Bengaluru",3 - 7 years,Structure the available data to be able to bet...
19,Data Scientist Machine Learning,Delhivery4.2(1511 Reviews),Gurgaon/Gurugram,1 - 3 years,Data Scientist Machine Learning Apply Descript...

## Q.4 Glassdoor job search

In [97]:
# let's connect to thewebdriver
driver=webdriver.Chrome('chromedriver.exe')

# open the glassdoor url in driver
url="https://www.glassdoor.co.in/index.htm"
driver.get(url)

# add timer to give driver time to load the webpage
time.sleep(2)

# get sign-in button web element
sign_in_btn=driver.find_element_by_xpath("//button[@class='d-none d-lg-block p-0 LockedHomeHeaderStyles__signInButton']")
# click on the sign-in button
sign_in_btn.click()


# get web-element for username bar
user_name=driver.find_element_by_id('userEmail')
# write the username
user_name.send_keys("ashish7@sharklasers.com")
# get web-element for password bar:
password=driver.find_element_by_id('userPassword')
# write the password
password.send_keys("8208507760")
# get webelement for sign-in button
sign=driver.find_element_by_xpath("//button[@class='gd-ui-button minWidthBtn css-8i7bc2']")
# click on the sign button
sign.click()



# add timer to give driver time to load the webpage
time.sleep(2)


# get the web-element for job search bar
job_search=driver.find_element_by_id('sc.keyword')
# enter the 'Data Scientist' text onto search bar
job_search.send_keys("Data Scientist")
#get the web-element for location search bar
loc_search=driver.find_element_by_id('sc.location')
# delete the existing text from location search bar
loc_search.send_keys(Keys.CONTROL+'a',Keys.BACKSPACE)
# enter the 'Noida' in location search bar
loc_search.send_keys("Noida")
# get webelement for 'search' button
search_btn=driver.find_element_by_xpath("//button[@data-test='search-bar-submit']")
# clicking the search button
search_btn.click()

# add timer to give driver time to load the webpage
time.sleep(2)

# get job titles info
# get job title tags
title_tag=driver.find_elements_by_xpath("//a[@class='jobLink css-1rd3saf eigr9kq2']")
# crete job titles list and initiate it
titles=[]
titles.clear()
for i in title_tag:
    titles.append(i.text)
    if len(titles)==10:
        break

#get company info
#get company name tags
comp_tag=driver.find_elements_by_xpath("//div[@class='d-flex justify-content-between align-items-start']")
#create companies list and initiate it
companies=[]
companies.clear()
for i in comp_tag:
    companies.append(i.text)
    if len(companies)==10:
        break

    
# get the location info
# get the location tags
loc_tag=driver.find_elements_by_xpath("//div[@class='d-flex flex-wrap css-11d3uq0 e1rrn5ka2']//span")
#create the loction list and initiate it
locations=[]
locations.clear()
for i in loc_tag:
    locations.append(i.text)
    if len(locations)==10:
        break

    
descriptions=[]
descriptions.clear()


for i in range(0,len(titles)):
    #storing the webelement for [i]th job description
    temp_tag=title_tag[i]
    
    if i==1:
    #getting webelement of Activate button of pop up of email notifications
        activ_btn=driver.find_element_by_xpath("//button[@class='gd-ui-button  e8e8plt0 css-1kp7eb7']")
    #click on activate button
        activ_btn.click()
    #getting webelement of 'x' close
        close_btn=driver.find_element_by_xpath("//span[@class='SVGInline modal_closeIcon']")
    # clicking on the close
        close_btn.click()
    
    #clicking on the [i]th job description
    temp_tag.click()
    
    # get webelement for job description
    descr_tag=driver.find_element_by_xpath("//div[@class='jobDescriptionContent desc']")
    # get text from above tag and append it to job description list
    descriptions.append(descr_tag.text.replace("\n"," "))

# add timer to give driver time to load the webpage
time.sleep(2)

driver.quit()

jobs_2=pd.DataFrame({})    
#enter data into dataframe
jobs_2['titles']=titles
jobs_2['company']=companies
jobs_2['Location']=locations
jobs_2['Job Description']=descriptions

In [98]:
jobs_2

,titles,company,Location,Job Description
0,Data Scientist,Biz2Credit Inc,Noida,"Job Description About the Role: This is a rare opportunity to join a small but fast-growing team, where you will play a major role in shaping Biz2Credit?s future. We?re looking for an exceptional candidate that is excited about the opportunity to build a next-generation financial services business. We believe that there is a tremendous opportunity to leverage cutting-edge data science to inform smarter, faster decision making. As a Biz2Credit Data Scientist, you will shape the company?s data-centric culture, work closely with our engineering team to develop our analytics infrastructure, and collaborate closely with our Chief Data Officer on developing, validating, and automating our customer conversion and underwriting models. While a background in financial services is not required, you must be passionate about tackling complex data challenges for the benefit of small and medium businesses everywhere."
1,Data Scientist,Techlive,Noida,Co-relationship models Exponential Moving Average Smoothened Exponential Moving Average Croston Requirement Good Oral and Written Communication Skills Data Digger/Data Analyst Analytical
2,Data Scientist,Ericsson,Noida,"As the tech firm that created the mobile world, and with more than 54,000 patents to our name, we’ve made it our business to make a mark. When joining our team at Ericsson you are empowered to learn, lead and perform at your best, shaping the future of technology. This is a place where you're welcomed as your own perfectly unique self, and celebrated for the skills, talent, and perspective you bring to the team. Are you in? Come, and be where it begins. Our Exciting Opportunity : As Data Scientist, you will be in developing scientific methods, processes, and systems to extract knowledge or insights to drive the future of applied analytics and Provide thought leadership, perform complex Statistical Analytics, and build insights into data to deliver to the business measurable insights, identify trends, and measure performance which address business problems!"
3,Applied Data Scientist,dunnhumby,Gurgaon,"Gurgaon Most companies try to meet expectations, dunnhumby exists to defy them. Using big data, deep expertise and AI-driven platforms to decode the 21st century human experience – then redefine it in meaningful and surprising ways that put customers first. Across digital, mobile and retail. For brands like Tesco, Coca-Cola, Procter & Gamble and PepsiCo. We’re looking for an Applied Data Scientist who expects more from their career. It’s a chance to apply your expertise to distil complex problems into compelling insights using the best of machine learning and human creativity to deliver effective and impactful solutions for clients. Joining our advanced data science team, you’ll investigate, develop, implement and deploy a range of complex applications and components while working alongside super-smart colleagues challenging and rewriting the rules, not just following them. What we expect from you 3 to 5 years of experience required Degree in Statistics, Maths, Physics, Economics or similar field Programming skills (Python and SQL are a must have) Analytical Techniques and Technology Experience with and passion for connecting your work directly to the customer experience, making a real and tangible impact. Logical thinking and problem solving Strong communication skills Statistical Modelling and experience of applying data science into client problems What you can expect from us We won’t just meet your expectations. We’ll defy them. So you’ll enjoy the comprehensive rewards package you’d expect from a leading technology company. But also, a degree of personal flexibility you might not. Plus, thoughtful perks, like early finish Friday and your birthday off. You’ll also benefit from an investment in cutting-edge technology that reflects our global ambition. But with a nimble, small-business feel that gives you the freedom to play, experiment and learn. And we don’t just talk about diversity and inclusion. We live it every day – with thriving networks including dh Women’s Network, dh Proud, dh Parent’s & Carer’s, dh One and dh Thrive as the living proof. Everyone’s invited. Our approach to Flexible Working At dunnhumby, we value and respect difference and are committed to building an inclusive culture by creating an environment where you can balance a successful career with your commitments and interests outside of work. We believe that you will do your best at work if you have a work / life balance. Some roles lend themselves to flexible options more than others, so if this is important to you please raise this with your recruiter, as we are open to discussing agile working opportunities during the hiring process. For further information about how we collect and use your personal information please see our Privacy Notice"
4,Data Scientist - Computer Vision,CRMNEXT,Noida,"Job Description Roles and Responsibilities As a Computer Vision Rockstar, you will be a core member of our high-impact AI team solving real world problems using state-of-the-art computer-vision techniques. Apart from working on computer vision, the person in this role will also be working in areas of Natural Language Processing (NLP) and time-series forecasting using neural models. As a member of our team, you would work in an exciting and fast-paced environment, collaborating with product teams and others across the company. You will focus on designing, implementing, and maintaining various end-to-end ML pipelines with a focus on building products leveraging computer vision technologies."
5,Data Scientist,Salasar New Age Technologies,Noida,"Hiring Data Scientists with 1-3 year of experience for our Noida office, should be open to relocate to US. Broad expectations: Research, develop and prototype algorithms to solve problems in video/image content analysis. Demonstrate and Document working prototype on test datasets and real world scenarios. Inter teams Interface to ensure timely delivery of high quality products. Innovate to come up with new solutions and improve existing solutions. Be an enthusiastic and motivated member of the team. Maintain knowledge of new technologies in the field of Computer Vision and Machine Learning."
6,"Data Scientist - Gurgaon, HR",UnitedHealth Group,Gurgaon,"Combine two of the fastest-growing fields on the planet with a culture of performance, collaboration and opportunity and this is what you get. Leading edge technology in an industry that's improving the lives of millions. Here, innovation isn't about another gadget, it's about making health care data available wherever and whenever people need it, safely and reliably. There's no room for error. Join us and start doing your life's best work.(sm) Primary Responsibilities: Lead multiple projects in data science Manage client and program engagements using governance models Work closely with leadership in devising strategy for pioneering and implementing advanced analytics methods to identify and solve business problems in healthcare"
7,Data Scientist,WishFin,Noida,"OVERVIEW We are looking at onboarding Data Scientist with the primary responsibility of designing analytic based strategies & quantitative model for business insight in the space of Banking, Capital Markets and Insurance. KEY RESPONSIBILITIES: Developing problem statements and high quality quantitative models for business insight in the space of Banking, Capital Markets and Insurance Designing analytic strategies to meet the demands of business Defines the technical requirements of the analytic solutions"
8,Data Scientist Intern,Salasar New Age Technologies,Noida,"Hiring interns with a tremendous desire to learn new/futuristic technologies by continuous research and experimentation, developing prototypes, demonstrating proof of concepts and convert their ideas into products in short spans. Work on OpenCV, SimpleCV or ilastik Acquire Data Refine Data Develop model Train Model Update technical documentation Dedicated full time internship (Noida)"
9,Data Scientist – Voice & NLP,CRMNEXT,Noida,"Job Description Roles and Responsibilities We are currently looking for a passionate, innovative and dynamic Rockstars to join a high impact AI team aiming for the moon. We are on a mission to disrupt the CRM space through Digital transformation. The role will involve designing components & building ML pipelines from scratch, architecting low latency systems at scale. If you are excited about, owning & building a next generation Conversational AI platform and working on core algorithms, right from training to production, you’ll love the job. What You Will Do"

## Q.5  glassdoor Salary Scraping

In [12]:
# let's connect to thewebdriver
driver=webdriver.Chrome('chromedriver.exe')

# maximize
driver.maximize_window()

# open the glassdoor url in driver
url="https://www.glassdoor.co.in/Salaries/index.htm"
driver.get(url)

# get sign-in button web element
sign_in_btn=driver.find_element_by_xpath("//button[@class='d-none d-lg-block p-0 LockedHomeHeaderStyles__signInButton']")
# click on the sign-in button
sign_in_btn.click()


# get web-element for username bar
user_name=driver.find_element_by_id('userEmail')
# write the username
user_name.send_keys("ashish7@sharklasers.com")
# get web-element for password bar:
password=driver.find_element_by_id('userPassword')
# write the password
password.send_keys("8208507760")
# get webelement for sign-in button
sign=driver.find_element_by_xpath("//button[@class='gd-ui-button minWidthBtn css-8i7bc2']")
# click on the sign button
sign.click()

# add timer to give driver time to load the webpage
time.sleep(2)

#get the job search bar webelement
job_search=driver.find_element_by_xpath("//input[@name='sc.keyword']")
# write the text into search bar
job_search.send_keys("Data Scientist")

# get the location search bar web-element
loc_search=driver.find_element_by_id("LocationSearch")
# remove the existing text
loc_search.send_keys(Keys.CONTROL+'a',Keys.BACKSPACE)
# write the text into location search bar
loc_search.send_keys("Noida")

# get webelement for search button
search_btn=driver.find_element_by_xpath("//button[@id='HeroSearchButton']")
# click on the search button
search_btn.click()

# add timer to give driver time to load the webpage
time.sleep(2)

# get web element for job comp name
comp_wbe=driver.find_elements_by_xpath("//div[@data-test='job-info']")
# get text from above webelements
comps=[]
comps.clear()
temp_comps=[]
temp_comps.clear()
for i in comp_wbe:
    temp_comps.append(i.text)
    if len(temp_comps)==10:
        break
        
for i in temp_comps:
    comps.append(i.replace("\n",',').split(',')[1])

# get min max salary webelement
minmax_wbe=driver.find_elements_by_xpath("//div[@class='common__RangeBarStyle__rangeBar undefined undefined ']")
#get text from above webelement
sal_range=[]
sal_range.clear()
for i in minmax_wbe:
    sal_range.append(i.text)
    if len(sal_range)==10:
        break

min_sal=[]
max_sal=[]
min_sal.clear()
max_sal.clear()
for i in sal_range:
    min_sal.append(i.replace("\n"," ").split(" ")[0])
    max_sal.append(i.replace("\n"," ").split(" ")[1])

    
    
#get webelement for average salary
avg_sal_wbe=driver.find_elements_by_xpath("//div[@class='col-2 d-none d-md-flex flex-row justify-content-end']")
# get text from above
avg_sal=[]
avg_sal.clear()
for i in avg_sal_wbe:
    avg_sal.append(i.text)
    if len(avg_sal)==10:
        break

avg_sal_1=[]
avg_sal_1.clear()
for i in avg_sal:
    avg_sal_1.append(i.replace("\n"," "))

#driver.quit()

# create dataframe
job_4=pd.DataFrame({})
job_4['Companies']=comps
job_4['Min Salary']=min_sal
job_4['Max Salary']=max_sal
job_4['Average Salary']=avg_sal_1

In [13]:
job_4

                   Companies Min Salary Max Salary   Average Salary
0  Tata Consultancy Services      ₹343K    ₹1,095K   ₹ 6,11,228 /yr
1                  Accenture      ₹577K    ₹2,213K  ₹ 11,46,533 /yr
2                        IBM      ₹586K    ₹2,730K   ₹ 8,97,795 /yr
3         Ericsson-Worldwide      ₹355K    ₹1,613K   ₹ 7,38,057 /yr
4                  Delhivery      ₹450K   ₹11,622K  ₹ 12,39,781 /yr
5         UnitedHealth Group    ₹1,069K    ₹1,520K  ₹ 13,36,142 /yr
6         Valiance Solutions      ₹502K    ₹1,465K   ₹ 8,15,192 /yr
7              ZS Associates      ₹202K    ₹1,809K  ₹ 11,35,221 /yr
8                EXL Service      ₹575K    ₹1,520K  ₹ 11,44,243 /yr
9     Optum Global Solutions    ₹1,014K    ₹2,149K  ₹ 14,13,288 /yr

## Q.6 Scrape data of first 100 sunglasses listings on flipkart.com

In [57]:
def fetch_data():
    # get web element for brand name
    brand_wbe=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
    #get brand name text
    for i in brand_wbe:
        brands.append(i.text)
        if len(brands)==100:
            break
        
    # get web element for Price
    price_wbe=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
    # get price text from above
    for i in price_wbe:
        prices.append(i.text)
        if len(prices)==100:
            break

    #get web element for discount
    disc_wbe=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']")
    # get text from above
    for i in disc_wbe:
        discounts.append(i.text)
        if len(discounts)==100:
            break

    #get web element for product description
    descr_wbe=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
    # get text from above
    for i in descr_wbe:
        descriptions.append(i.text)
        if len(descriptions)==100:
            break

In [63]:
# connect to the chrome webdriver
driver=webdriver.Chrome('chromedriver.exe')

# enter the url
url="https://www.flipkart.com/"
driver.get(url)

#add timer sleep
time.sleep(2)

# get web element for login email search bar
email_wbe=driver.find_element_by_xpath("//input[contains(@class,'_2IX_2-')]")#@class='_2IX_2- _2LYh3d VJZDxU'
# enter the email id
email_wbe.send_keys("8208507760")

#get web element for password bar
pwd_wbe=driver.find_element_by_xpath("//input[@type='password']")#class='_2IX_2- _3mctLh VJZDxU'
# enter the password
pwd_wbe.send_keys("Newpassword@72")

# get the webelement for login button
login_btn=driver.find_element_by_xpath("//button[@class='_2KpZ6l _2HKlqd _3AWRsL']")
#click on login button
login_btn.click()

#add timer sleep
time.sleep(3)

# get the web element for search bar
search_wbe=driver.find_element_by_xpath("//input[@name='q' and @placeholder='Search for products, brands and more']")
# write into search bar and pressing ENTER 
search_wbe.send_keys("sunglasses",Keys.ENTER)

#add timer sleep
time.sleep(3)


brands=[]
brands.clear()
        
prices=[]
prices.clear()

discounts=[]
discounts.clear()

descriptions=[]
descriptions.clear()

# get web element for page button
page_wbe=driver.find_elements_by_xpath("//a[contains(@class,'ge-49M')]")
# get urls of each page
page_urls=[]
page_urls.clear()

#to store page numbers
page_numbers=[]
page_numbers.clear()

# get urls of each next page from webelement
for i in page_wbe:
    temp_url= i.get_attribute('href')
    page_urls.append(temp_url)
    page_numbers.append(i.text)
    
    
counter=0   
for url in page_urls:
    if counter==0:
        fetch_data()
        counter=1
    else:
        if len(brands)==100:
            break
        else:
            main_window=driver.current_window_handle
            
            driver.execute_script("window.open('about:blank','secondtab');")
            
            driver.switch_to.window('secondtab')
            
            driver.get(url)
            
            time.sleep(3)
            
            fetch_data()
            
            driver.close()
            
            driver.switch_to.window(main_window)


#close the driver
driver.quit()

# create the dataframe
glasses=pd.DataFrame({})
glasses['Brand Name']=brands
glasses['Price']=prices
glasses['Discount']=discounts
glasses['Product Description']=descriptions

In [64]:
glasses

,Brand Name,Price,Discount,Product Description
0,Fastrack,₹630,21% off,UV Protection Rectangular Sunglasses (Free Size)
1,GANSTA,₹281,85% off,UV Protection Aviator Sunglasses (57)
2,ROZZETTA CRAFT,₹499,77% off,UV Protection Retro Square Sunglasses (Free Size)
3,DEIXELS,₹202,83% off,"UV Protection Aviator, Wayfarer Sunglasses (Free Size)"
4,PIRASO,₹349,78% off,UV Protection Aviator Sunglasses (Free Size)
...,...,...,...,...
95,ROYAL SON,₹759,62% off,"Polarized, UV Protection Retro Square Sunglasses (60)"
96,Fastrack,"₹1,148",11% off,UV Protection Aviator Sunglasses (58)
97,ROYAL SON,₹569,71% off,UV Protection Retro Square Sunglasses (88)
98,Fastrack,"₹1,097",15% off,UV Protection Rectangular Sunglasses (59)
99,ROYAL SON,₹499,66% off,UV Protection Rectangular Sunglasses (Free Size)

### Q.7 Scrape 100 reviews data from flipkart.com for iphone11 phone.

In [48]:
def fetch_data():
    # get webelement for rating
    rate_wbe=driver.find_elements_by_xpath("//div[contains(@class,'_3LWZlK _')]")
    #get text from above
    for i in rate_wbe:
        ratings.append(i.text)

    # get web element for short review
    short_wbe=driver.find_elements_by_xpath("//div[@class='row']//p[@class='_2-N8zT']")
    # get text from above
    for i in short_wbe:
        short_rev.append(i.text)

    # get wbe for full review
    full_wbe=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']//div[@class='row']//div[@class='t-ZTKy']")
    # get text from above
    for i in full_wbe:
        full_rev.append(i.text.replace("\n"," "))

In [50]:
# lets connect to the webdriver
driver=webdriver.Chrome('chromedriver.exe')

# lets enter the url
url="https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace"
driver.get(url)

#add timer
time.sleep(3)

# get web element for all reviews link
all_reviews_wbe=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
# click on above wbe
all_reviews_wbe.click()


#add time
time.sleep(3)

# get web element for page button
page_wbe=driver.find_elements_by_xpath("//a[contains(@class,'ge-49M')]")
# get urls of each page
page_urls=[]
page_urls.clear()

page_numbers=[]
page_numbers.clear()

for i in page_wbe:
    temp_url= i.get_attribute('href')
    page_urls.append(temp_url)
    page_numbers.append(i.text)


ratings=[]
ratings.clear()

short_rev=[]
short_rev.clear()

full_rev=[]
full_rev.clear()    
    
# counter to keep track of pages    
counter=0   
for url in page_urls:
    if counter==0:
        fetch_data()
        counter=1
    else:
        main_window=driver.current_window_handle
            
        driver.execute_script("window.open('about:blank','secondtab');")
            
        driver.switch_to.window('secondtab')
            
        driver.get(url)
            
        time.sleep(3)
            
        fetch_data()
            
        driver.close()
            
        driver.switch_to.window(main_window)
            
# create dataframe
reviews=pd.DataFrame({})
reviews['Iphone-11 Rating']=ratings
reviews['Short Review']=short_rev
reviews['Full Review']=full_rev

reviews

,Iphone-11 Rating,Short Review,Full Review
0,5,Brilliant,"The Best Phone for the Money The iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price. Compelling ultra-wide camera New Night mode is excellent Long battery life"
1,5,Perfect product!,Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .
2,5,Great product,"Amazing Powerful and Durable Gadget. I’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone. I shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years. Don’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb. I’ve attached my puppy pics and no fi... READ MORE"
3,5,Worth every penny,Previously I was using one plus 3t it was a great phone And then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11 I have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD display But I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product red My experience after using 3 weeks 1. The delivery ... READ MORE
4,4,Good choice,So far it’s been an AMAZING experience coming back to iOS after nearly a decade but it’s not as versatile as android though phone is sturdy dropped it accidentally a couple of times and nothing happened fortunately camera is awesome
...,...,...,...
95,5,Best in the market!,The best all rounder iphone. Flipkart is doing a great job. They're delivery services are blazing fast. I got delivery on the same day. Genuine Apple Product. Working great. Talking about review There's no need of review for iphones. They're simply the best.
96,5,Terrific purchase,"Well , as we all know if its not an Iphone , its not an iphone . The iphones are always beast . The camera game has been level up . The A13 Bionic is just fabulous . The update this year are certainly the camera which is damn good with d addition of wide angle lens as well as ultra wide . If anyones purchasing an iphone for the first time , do opt for the black color . Its just feels more than premium . Battery life is damn good with lasting fully a day . Overall a nice package . Well managed... READ MORE"
97,5,Excellent,A perfect phone and a good battery super camera and the sound is dynamic overall the phone is perfect for upgrading from lower iPhone model to iPhone 11
98,5,Fabulous!,Everything is perfect pictures come out so clearly and at first I wasn’t sure when I got it then when I started to use it and get the hang of it it was amazing!! I can’t wait to see what the next future phones will be like. The screen display on this bad boy are unbelievable they are so clear and never fail me. The performance is super cool there is a lot of cool features as well I like this phone because I feel that it is easy to use and one of my favorite things about this phone is the Face... READ MORE
99,5,Wonderful,Nice value for money good and best price I phone mind blowing camera processor very fast other android mobile I am happy India top selling phone 2020

### Q.8 Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field.

In [70]:
def fetch_data():
    # get web element for brand name
    brand_wbe=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
    #get brand name text
    for i in brand_wbe:
        brands.append(i.text)
        if len(brands)==100:
            break
        
    # get web element for Price
    price_wbe=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
    # get price text from above
    for i in price_wbe:
        prices.append(i.text)
        if len(prices)==100:
            break

    #get web element for discount
    disc_wbe=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']")
    # get text from above
    for i in disc_wbe:
        discounts.append(i.text)
        if len(discounts)==100:
            break

    #get web element for product description
    descr_wbe=driver.find_elements_by_xpath("//a[contains(@class,'IRpwTa')]")
    # get text from above
    for i in descr_wbe:
        descriptions.append(i.text)
        if len(descriptions)==100:
            break

In [71]:
# connect to the chrome webdriver
driver=webdriver.Chrome('chromedriver.exe')

# enter the url
url="https://www.flipkart.com/"
driver.get(url)

#add timer sleep
time.sleep(2)

# get web element for login email search bar
email_wbe=driver.find_element_by_xpath("//input[contains(@class,'_2IX_2-')]")#@class='_2IX_2- _2LYh3d VJZDxU'
# enter the email id
email_wbe.send_keys("8208507760")

#get web element for password bar
pwd_wbe=driver.find_element_by_xpath("//input[@type='password']")#class='_2IX_2- _3mctLh VJZDxU'
# enter the password
pwd_wbe.send_keys("Newpassword@72")

# get the webelement for login button
login_btn=driver.find_element_by_xpath("//button[@class='_2KpZ6l _2HKlqd _3AWRsL']")
#click on login button
login_btn.click()

#add timer sleep
time.sleep(3)

# get the web element for search bar
search_wbe=driver.find_element_by_xpath("//input[@name='q' and @placeholder='Search for products, brands and more']")
# write into search bar and pressing ENTER 
search_wbe.send_keys("sneakers",Keys.ENTER)

#add timer sleep
time.sleep(3)


brands=[]
brands.clear()
        
prices=[]
prices.clear()

discounts=[]
discounts.clear()

descriptions=[]
descriptions.clear()

# get web element for page button
page_wbe=driver.find_elements_by_xpath("//a[contains(@class,'ge-49M')]")
# get urls of each page
page_urls=[]
page_urls.clear()

#to store page numbers
page_numbers=[]
page_numbers.clear()

# get urls of each next page from webelement
for i in page_wbe:
    temp_url= i.get_attribute('href')
    page_urls.append(temp_url)
    page_numbers.append(i.text)
    
    
counter=0   
for url in page_urls:
    if counter==0:
        fetch_data()
        counter=1
    else:
        if len(brands)==100:
            break
        else:
            main_window=driver.current_window_handle
            
            driver.execute_script("window.open('about:blank','secondtab');")
            
            driver.switch_to.window('secondtab')
            
            driver.get(url)
            
            time.sleep(3)
            
            fetch_data()
            
            driver.close()
            
            driver.switch_to.window(main_window)


#close the driver
#driver.quit()

# create the dataframe
sneakers=pd.DataFrame({})
sneakers['Brand Name']=brands
sneakers['Price']=prices
sneakers['Discount']=discounts
sneakers['Product Description']=descriptions

In [72]:
sneakers

,Brand Name,Price,Discount,Product Description
0,Robbie jones,₹399,60% off,Casual Sneakers Shoes For Men Sneakers For Men
1,aadi,₹298,70% off,Sneakers For Men
2,Robbie jones,₹474,52% off,Sneakers For Men
3,Numenzo,₹398,60% off,Sneakers For Men
4,Shoes Bank,₹349,65% off,White Sneaker For Men's/Boy's Sneakers For Men
...,...,...,...,...
95,JUBENTA,₹549,42% off,Latest Design Sneakers For Men
96,PUMA,"₹2,899",55% off,Puma Rebound LayUp SL Sneakers For Men
97,Arohi,₹445,60% off,Sneakers For Men
98,Adies,₹395,60% off,Sneakers For Men
99,bacca bucci,₹996,75% off,Men's Ultraforce Mid-top Athletic-Inspired Retro Fashio...

### Q.9 - Scraping myntra website for black shoes with price filtering

In [48]:
def fetch_data():
    # get webelement for brand name
    brand_wbe=driver.find_elements_by_xpath("//div[@class='product-productMetaInfo']/h3")
    #get text
    for i in brand_wbe:
        brands.append(i.text)
        if len(brands)==100:
            break
    
        
    #get webelement for product description
    descr_wbe=driver.find_elements_by_xpath("//div[@class='product-productMetaInfo']/h4[@class='product-product']")
    # get text
    for i in descr_wbe:
        descriptions.append(i.text)
        if len(descriptions)==100:
            break
    
    #get webelement for price
    price_wbe=driver.find_elements_by_xpath("//div[@class='product-price']/span[1]")
    #get text
    for i in price_wbe:
        if len(prices)==100:
            break
        else:
            temp_text=i.text
            if len(temp_text)<9:
                prices.append(temp_text)
            else:
                temp_text2=temp_text.split('Rs. ')[1]
                prices.append("Rs. "+temp_text2)

In [52]:
# connect to the chrome webdriver
driver=webdriver.Chrome('chromedriver.exe')

# enter the url
url="https://www.myntra.com/shoes"
driver.get(url)

#add timer sleep
time.sleep(2)

# get webelement for price filters
price_range_wbe=driver.find_element_by_xpath("//input[@class='price-input' and @value='6649.0 TO 13099.0']//following-sibling::div[@class='common-checkboxIndicator']")

# click
price_range_wbe.click()

#add timer sleep
time.sleep(2)

# get webelement for black color filter
black_wbe=driver.find_element_by_xpath("//input[@type='checkbox' and @value='Black']//following-sibling::div[@class='common-checkboxIndicator']")
#click
black_wbe.click()

# get web element for page number urls
pg_number=driver.find_elements_by_xpath("//li[@class='pagination-number']//a")
# get urls 
pg_urls=[]
pg_urls.clear()
for i in pg_number:
    temp_url=i.get_attribute('href')
    pg_urls.append(temp_url)


brands=[]
brands.clear()    
descriptions=[]
descriptions.clear()
prices=[]
prices.clear()




# counter for page number
counter=1
#getting data 
if counter==1:
    fetch_data()
    counter=2
if counter==2:
    for url in pg_urls:
        if len(brands)==100:
            break
        else:
            main_window=driver.current_window_handle
            
            driver.execute_script("window.open('about:blank','secondtab');")
            
            driver.switch_to.window('secondtab')
            
            driver.get(url)
            
            time.sleep(3)
            
            fetch_data()
            
            driver.close()
            
            driver.switch_to.window(main_window)

# create the dataframe
shoes=pd.DataFrame({})
shoes['Brand Name']=brands
shoes['Price']=prices
shoes['Product Description']=descriptions 

shoes

         Brand Name      Price             Product Description
0              Nike  Rs. 11495  AIR ZOOM PEGASUS Running Shoes
1              Nike  Rs. 12495     Men JORDAN DELTA Basketball
2              Nike  Rs. 10121          Women AIR ZOOM Running
3   PUMA Motorsport   Rs. 7999   Unisex Mercedes Running Shoes
4              Nike  Rs. 12995    Men KD13 EP Basketball Shoes
..              ...        ...                             ...
95            Ruosh   Rs. 6990              Men Formal Brogues
96          Saint G  Rs. 11800            Leather Heeled Boots
97             FILA   Rs. 6999            Women Solid Sneakers
98           ADIDAS   Rs. 7999     Men Supernova Running Shoes
99     Kenneth Cole   Rs. 9513          Women Solid Flat Boots

[100 rows x 3 columns]

### Q.10 Amazon Laptop scraping

In [76]:
# connect to the webdriver
driver=webdriver.Chrome('chromedriver.exe')

# enter the url
url='https://www.amazon.in/'
driver.get(url)

#add timer
time.sleep(3)

driver.maximize_window()

# get the webelement for search bar
search_wbe=driver.find_element_by_xpath("//input[@type='text' and @id='twotabsearchtextbox']")
#enter into search bar
search_wbe.send_keys("Laptop",Keys.ENTER)


#add timer
time.sleep(3)

# get webelement of 1st filter
i7_wbe=driver.find_element_by_xpath("//li[@id='p_n_feature_thirteen_browse-bin/12598163031']//following::i")
#click
i7_wbe.click()

# get webelement for title
title_wbe=driver.find_elements_by_xpath("//div[@class='a-section a-spacing-none']")
titles=[]
titles.clear()
for i in title_wbe:
    titles.append(i.text)
    if len(titles)==10:
        break

# get webelement for rating
rating_wbe=driver.find_elements_by_xpath("//span[@data-hook='acr-average-stars-rating-text' and @class='a-size-medium a-color-base a-text-beside-button a-text-bold']")
ratings=[]
ratings.clear()
for i in rating_wbe:
    ratings.append(i.text)
    if len(ratings)==10:
        break

# get webelement for price
price_wbe=driver.find_elements_by_xpath("//span[@class='a-price-whole']")
prices=[]
prices.clear()
for i in price_wbe:
    prices.append(i.text)
    if len(prices)==10:
        break

#add timer
#time.sleep(3)

# get webelement for 2nd filter
#i9_wbe=driver.find_element_by_xpath("//li[@id='p_n_feature_thirteen_browse-bin/16757432031']")
#click
#i9_wbe.click()

In [80]:
rating_wbe

[]